### PR TITLE
Pmw57 linting

### PR DESCRIPTION
**Pull request by pmw57**
As you're working through the A Good Parts book, your code is now linted according to JSLint.

### CODE REVIEW

**Comment by MarcoLucidi01** [comment]
Thank you for you effort.
I have not read the JSLint appendix nor the style chapter yet.

- Why the `Position` constructor is now called `makePosition` while `Food` has not changed?
- `getElapsedTimeHMS` looks really awkward now, I don't like it. Is the style "forced" by the linter?
- The game is broken now. It gets some type errors while eating foods and it doesn't perform any food action. Maybe `game.game.*` is wrong in foods actions?

**Comment by pmw57** [comment]
The errors have all been fixed by replacing game.game and food.game references to just the game.

The pattern for code that creates things is to prefix it with make. People wanted to use a create prefix, but that's confusing with Object.create instead so make was the choice. I've renamed makePosition to just position, as that flows better with the intended usage.

I agree about how getElapsedTimeHMS looks awkward, it is forced by the linter, which helps to force out bad coding design issues. A better solution is to use functions for common repeated parts of the code, which can be looked at next.

**Comment by pmw57** [comment]
You'll find that with the inclusion of a simple pad() function to the time, that the linted code is now much better than before.

                return pad(h) + ":" + pad(m) + ":" + pad(s);

**Comment by MarcoLucidi01** [comment]
Hi, sorry for the late reply, I've had a busy week.
The game runs fine now and I like the `pad` function used to solve that "awkwardness".
I understood all the changes more or less, but I still have few questions regarding `Food` and `position`:

- `Food` is capitalized while `position` is not. New foods are created using the `new` keyword, while new positions are created simply invoking `position` function. Methods of `Food` are implemented inside the object which is "assigned", while the `equals` method of `position` is implemented outside the "assigned" object.
Why there are these differences?
Is it correct to use the `new` keyword with a constructor implemented the way `Food` is implemented?

- `game` property of `Food` is useless since its methods now use the "global" `game` object. Am I right?

**Comment by pmw57** [comment]
Food is currently a constructor, that does things using "magic". That's something that's not appreciated by Douglas Crockford for several good reasons, and converting that is something that I want to leave for a different pull request.

I agree that the game property doesn't belong with food. It's not appropriate for food to have access to all of those game details.

The game object is not global, but is local to the IIFE wrapper function, and is accessible to everything inside but not to anything outside of it. I've moved the game object up to the top of that function to help reinforce that idea.

Next up I want to remove the tight coupling between the food and the game functions, but that's something that's best done as a separate pull request too.

**Comment by MarcoLucidi01** [comment]
All right, thank you for the clarifications.

**Pull request merged**
